---

all:
  vars:
    ansible_user: ck8sadm
    ansible_ssh_private_key_file: ~/.ssh/id_juju
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    ssh_user: ck8sadm
    juju_controller_ip: 192.168.184.50

  children:
    control_planes:
      hosts:
        cp01:
          ansible_host: 10.60.31.24
          hostname: control-plane-1
        cp02:
          ansible_host: 10.60.31.25
          hostname: control-plane-2
        cp03:
          ansible_host: 10.60.31.26
          hostname: control-plane-3

    workers:
      hosts:
        cp01:  # same inventory hostname, dual role
        cp02:  # same inventory hostname, dual role
        cp03:  # same inventory hostname, dual role
        worker04:
          ansible_host: 10.60.31.27
          hostname: worker-4
